### ISSUE TITLE
Error deleting files in Docker testing environment

### ISSUE THREAD

**Issue by Keltena** [iftechfoundation/ifarchive-admintool#55]
(I'm on Windows 10 and set up my dev environment with Docker using [the instructions in TESTING.md](https://github.com/iftechfoundation/ifarchive-admintool/blob/main/TESTING.md#the-easy-way-use-docker).)

When I delete one of my uploaded test files using the Delete button, I get the following error screen:
```
500 Internal Error (user=zarf, POST /admin/arch/games)
Traceback (most recent call last):
  File "/var/ifarchive/wsgi-bin/tinyapp/app.py", line 80, in application
    ls = self.process(req)
         ^^^^^^^^^^^^^^^^^
  File "/var/ifarchive/wsgi-bin/tinyapp/app.py", line 177, in process
    return dofunc(req)
           ^^^^^^^^^^^
  File "/var/ifarchive/wsgi-bin/tinyapp/handler.py", line 46, in <lambda>
    self.do_post = lambda req: wrapper(req, han.do_post)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/ifarchive/wsgi-bin/tinyapp/auth.py", line 16, in func
    return han(req)
           ^^^^^^^^
  File "/var/ifarchive/wsgi-bin/tinyapp/handler.py", line 46, in <lambda>
    self.do_post = lambda req: wrapper(req, han.do_post)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/ifarchive/wsgi-bin/tinyapp/auth.py", line 33, in func
    return han(req)
           ^^^^^^^^
  File "/var/ifarchive/wsgi-bin/tinyapp/handler.py", line 46, in <lambda>
    self.do_post = lambda req: wrapper(req, han.do_post)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/ifarchive/wsgi-bin/adminlib/session.py", line 119, in find_user
    return han(req)
           ^^^^^^^^
  File "/var/ifarchive/wsgi-bin/tinyapp/handler.py", line 46, in <lambda>
    self.do_post = lambda req: wrapper(req, han.do_post)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/ifarchive/wsgi-bin/adminlib/session.py", line 127, in require_user
    return han(req)
           ^^^^^^^^
  File "/var/ifarchive/wsgi-bin/tinyapp/handler.py", line 46, in <lambda>
    self.do_post = lambda req: wrapper(req, han.do_post)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/ifarchive/wsgi-bin/admin.wsgi", line 1259, in check_archive_dir
    return han(req)
           ^^^^^^^^
  File "/var/ifarchive/wsgi-bin/admin.wsgi", line 563, in do_post
    return self.do_post_delete(req, dirpath, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/ifarchive/wsgi-bin/admin.wsgi", line 648, in do_post_delete
    os.utime(newpath)
PermissionError: [Errno 13] Permission denied
```
The file is successfully moved to `/trash`, but the index entry remains in the original folder.

I get this error with every file I've uploaded with `docker/upload-file.sh`, but not with the automatically-created backup Index files.

Other operations (Create/Delete Symlink, Create/Delete Directory, Move, Rename, Edit Index) work normally.

**Comment by erkyrath** [comment]
To be clear, the error is on touching mod time on the file in /trash. The routine throws an exception and never reaches the part about updating Index.

I imagine this just needs a `chown www-data $tmpfile` somewhere.
